export const dynamic = 'force-dynamic'
import { prisma } from '@/lib/prisma'
import { emailInvoiceSchema } from '@/lib/validations'
import { withValidation, withApiRateLimit } from '@/lib/api-wrapper'
import { handleApiError } from '@/lib/api-errors'
import {
  loadEmailSettings,
  isEmailConfigured,
  sendMail,
  loadCompanySettings,
  formatAmount,
  escapeHtml,
} from '@/lib/email'
import { logAudit } from '@/lib/audit'
import { getCurrentUser } from '@/lib/current-user'

function invoiceEmailHtml(opts: {
  companyName: string
  currency: string
  invoiceNumber: string
  invoiceType: string
  issueDate: string
  dueDate: string
  contactName: string
  items: { description: string; quantity: number; unitPrice: number; amount: number }[]
  subtotal: number
  taxAmount: number
  totalAmount: number
  paidAmount: number
  balanceDue: number
}): string {
  const itemRows = opts.items.length
    ? opts.items
        .map(
          (it) => `<tr>
            <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${escapeHtml(it.description)}</td>
            <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; text-align: center;">${it.quantity}</td>
            <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; text-align: right;">${formatAmount(it.unitPrice, opts.currency)}</td>
            <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; text-align: right;">${formatAmount(it.amount, opts.currency)}</td>
          </tr>`
        )
        .join('')
    : '<tr><td colspan="4" style="padding: 8px 12px; color: #94a3b8; text-align: center;">No line items</td></tr>'

  return `
    <div style="font-family: Arial, Helvetica, sans-serif; max-width: 640px; margin: 0 auto; color: #1e293b;">
      <div style="background: #0f172a; color: #fff; padding: 24px; border-radius: 8px 8px 0 0;">
        <h2 style="margin: 0;">${escapeHtml(opts.companyName)}</h2>
        <p style="margin: 4px 0 0; font-size: 13px; color: #cbd5e1;">Invoice ${escapeHtml(opts.invoiceNumber)}</p>
      </div>
      <div style="border: 1px solid #e2e8f0; border-top: none; padding: 24px; border-radius: 0 0 8px 8px;">
        <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
          <div>
            <p style="margin: 0; font-size: 13px; color: #64748b;">Bill To</p>
            <p style="margin: 4px 0 0; font-weight: 600;">${escapeHtml(opts.contactName)}</p>
          </div>
          <div style="text-align: right; font-size: 13px; color: #475569;">
            <p style="margin: 0;">Type: ${escapeHtml(opts.invoiceType)}</p>
            <p style="margin: 0;">Issue Date: ${escapeHtml(opts.issueDate)}</p>
            <p style="margin: 0;">Due Date: ${escapeHtml(opts.dueDate)}</p>
          </div>
        </div>
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          <thead>
            <tr style="background: #f8fafc; color: #64748b; text-align: left;">
              <th style="padding: 8px 12px;">Description</th>
              <th style="padding: 8px 12px; text-align: center;">Qty</th>
              <th style="padding: 8px 12px; text-align: right;">Unit Price</th>
              <th style="padding: 8px 12px; text-align: right;">Amount</th>
            </tr>
          </thead>
          <tbody>${itemRows}</tbody>
        </table>
        <table style="width: 100%; margin-top: 16px; font-size: 14px; border-collapse: collapse;">
          <tr><td style="padding: 4px 12px; color: #64748b;">Subtotal</td><td style="padding: 4px 12px; text-align: right;">${formatAmount(opts.subtotal, opts.currency)}</td></tr>
          <tr><td style="padding: 4px 12px; color: #64748b;">Tax</td><td style="padding: 4px 12px; text-align: right;">${formatAmount(opts.taxAmount, opts.currency)}</td></tr>
          <tr style="font-weight: 700;"><td style="padding: 8px 12px;">Total</td><td style="padding: 8px 12px; text-align: right;">${formatAmount(opts.totalAmount, opts.currency)}</td></tr>
          <tr><td style="padding: 4px 12px; color: #64748b;">Paid</td><td style="padding: 4px 12px; text-align: right;">${formatAmount(opts.paidAmount, opts.currency)}</td></tr>
          <tr style="font-weight: 700; color: #dc2626;"><td style="padding: 8px 12px;">Amount Due</td><td style="padding: 8px 12px; text-align: right;">${formatAmount(opts.balanceDue, opts.currency)}</td></tr>
        </table>
        <p style="margin-top: 24px; font-size: 14px; color: #475569;">
          Please find attached invoice details for ${escapeHtml(opts.invoiceNumber)}. Payment is due by ${escapeHtml(opts.dueDate)}.
          Kindly reference the invoice number on your payment. Thank you for your business!
        </p>
        <p style="margin-top: 24px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8;">
          This invoice was generated by BuildProp.
        </p>
      </div>
    </div>`
}

export const POST = withApiRateLimit(
  withValidation(emailInvoiceSchema, async (_request, body) => {
    try {
      const settings = await loadEmailSettings()
      if (!isEmailConfigured(settings)) {
        return Response.json(
          { error: 'Email is not configured. Go to Settings → Email to set up your SMTP account.' },
          { status: 400 }
        )
      }

      const invoice = await prisma.invoice.findUnique({
        where: { id: body.invoiceId },
        include: { items: true },
      })
      if (!invoice) {
        return Response.json({ error: 'Invoice not found' }, { status: 404 })
      }

      const contact = await prisma.contact.findUnique({
        where: { id: invoice.contactId },
      })
      if (!contact?.email) {
        return Response.json(
          { error: 'The client for this invoice has no email address on file.' },
          { status: 400 }
        )
      }

      const { companyName, currency } = await loadCompanySettings()

      const toNum = (v: unknown): number => {
        const num = Number(v)
        return isNaN(num) ? 0 : num
      }

      const items = (invoice.items || []).map((item) => ({
        description: item.description,
        quantity: toNum(item.quantity),
        unitPrice: toNum(item.unitPrice),
        amount: toNum(item.amount),
      }))

      const totalAmount = toNum(invoice.totalAmount)
      const paidAmount = toNum(invoice.paidAmount)
      const balanceDue = Math.max(totalAmount - paidAmount, 0)

      const html = invoiceEmailHtml({
        companyName,
        currency,
        invoiceNumber: invoice.invoiceNumber,
        invoiceType: invoice.type.charAt(0).toUpperCase() + invoice.type.slice(1),
        issueDate: new Date(invoice.issueDate).toLocaleDateString('en-GB'),
        dueDate: new Date(invoice.dueDate).toLocaleDateString('en-GB'),
        contactName: `${contact.firstName} ${contact.lastName}`,
        items,
        subtotal: toNum(invoice.subtotal),
        taxAmount: toNum(invoice.taxAmount),
        totalAmount,
        paidAmount,
        balanceDue,
      })

      const result = await sendMail({
        to: contact.email,
        subject: `Invoice ${invoice.invoiceNumber} from ${companyName}`,
        html,
      })

      if (!result.success) {
        return Response.json({ error: result.message }, { status: 500 })
      }

      try {
        const currentUser = await getCurrentUser()
        await logAudit('invoice_email', 'invoices', `Invoice ${invoice.invoiceNumber} emailed to ${contact.email}`, currentUser?.id)
      } catch {}

      return Response.json({ success: true, to: contact.email })
    } catch (error) {
      return handleApiError(error)
    }
  })
)
